<h1>Data Inspection</h1>

In [9]:
import pandas as pd

<h3>Create a Sample Dataset</h3>

In [10]:
students = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Arjun", "Rogan", "Prakash", "Jothi", "Mathi"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["AI", "ML", "DS", "AI", "ML"],
    "Marks": [95, 88, 91, 84, 89]
})

print(students)

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
1  102    Rogan   23         ML     88
2  103  Prakash   21         DS     91
3  104    Jothi   24         AI     84
4  105    Mathi   22         ML     89

<h2>head()</h2>

head() displays the first five rows of a DataFrame by default.

It is useful for quickly checking whether the dataset has been loaded correctly.

Syntax:

df.head()

We can also specify the number of rows.

df.head(n)

Example:

A data analyst loads a CSV file containing 1 million customer records. Instead of displaying the entire dataset, they use head() to verify that the data has been imported correctly.

<h3>AI/ML Usage</h3>
    
Used to quickly inspect datasets before preprocessing and model training.

In [11]:
students.head(3)

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
1  102    Rogan   23         ML     88
2  103  Prakash   21         DS     91

head() = Show me the beginning of my data.

<h2>tail()</h2>

tail() displays the last five rows of a DataFrame.

Example:

A company checks the latest customer transactions by viewing the last few rows of a daily sales dataset.

<h3>AI/ML Usage</h3>

Useful for verifying recently appended records in large datasets.

In [12]:
students.tail(2)

    ID   Name  Age Department  Marks
3  104  Jothi   24         AI     84
4  105  Mathi   22         ML     89

<h2>sample()</h2>

sample() returns randomly selected rows from a DataFrame.

Syntax:

df.sample(n)

Example:

A teacher randomly selects two students for an oral presentation.

<h3>AI/ML Usage</h3>
    
Used for random data inspection, testing, and creating sample datasets.

In [13]:
students.sample(2)

    ID   Name  Age Department  Marks
3  104  Jothi   24         AI     84
0  101  Arjun   22         AI     95

sample() = Give me some random records from my data.

<h2>info()</h2>

info() provides a summary of the DataFrame.

It displays:

<ul><li>Number of rows</li>
<li>Number of columns</li>
<li>Column names</li>
<li>Data types</li>
<li>Missing values</li>
<li>Memory usage</li></ul>

__Example:__

Before cleaning employee records, an HR analyst checks which columns have missing values and their data types.

<h3>AI/ML Usage</h3>
    
Used to understand the dataset before feature engineering and preprocessing.

In [14]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          5 non-null      int64
 1   Name        5 non-null      object
 2   Age         5 non-null      int64
 3   Department  5 non-null      object
 4   Marks       5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

info() = Tell me about the structure of my dataset.

<h2>describe()</h2>

describe() generates statistical summaries of numerical columns.

It provides:

<ul><li>Count</li>
<li>Mean</li>
<li>Standard deviation</li>
<li>Minimum</li>
<li>Maximum</li>
<li>Quartiles</li></ul>

__Example:__

A hospital calculates the average age and maximum age of patients.

<h3>AI/ML Usage</h3>
    
Used to identify outliers and understand feature distributions.

In [15]:
students.describe()

               ID        Age      Marks
count    5.000000   5.000000   5.000000
mean   103.000000  22.400000  89.400000
std      1.581139   1.140175   4.037326
min    101.000000  21.000000  84.000000
25%    102.000000  22.000000  88.000000
50%    103.000000  22.000000  89.000000
75%    104.000000  23.000000  91.000000
max    105.000000  24.000000  95.000000

<h3>shape</h3>

shape returns the number of rows and columns.

__Example:__

A company checks whether the downloaded sales dataset contains the expected number of records.

<h3>AI/ML Usage</h3>
    
Used to verify dataset size before model training.

In [16]:
students.shape

(5, 5)

<h2>columns</h2>

columns returns the names of all columns.

Example:

An analyst checks available columns before selecting features for analysis.

<h3>AI/ML Usage</h3>

Used for feature selection and column renaming.

In [17]:
students.columns

Index(['ID', 'Name', 'Age', 'Department', 'Marks'], dtype='object')

<h2>dtypes</h2>

dtypes displays the data type of every column.

__Example:__

A bank verifies whether transaction amounts are stored as numbers instead of text.

<h3>AI/ML Usage</h3>

Correct data types are required before applying machine learning algorithms.

In [18]:
students.dtypes

ID             int64
Name          object
Age            int64
Department    object
Marks          int64
dtype: object

<h2>memory_usage()</h2>

memory_usage() shows how much memory each column occupies.

__Example:__

A company working with millions of records checks memory usage to optimize storage and improve performance.

<h3>AI/ML Usage</h3>

Used to reduce memory consumption in large datasets.

In [19]:
students.memory_usage()

Index         132
ID             40
Name           40
Age            40
Department     40
Marks          40
dtype: int64

<h2>nunique()</h2>

nunique() returns the number of unique values in each column.

__Example:__

A supermarket checks how many different product categories are available.

<h3>AI/ML Usage</h3>

Helps identify categorical features and low-cardinality columns.

In [20]:
students.nunique()

ID            5
Name          5
Age           4
Department    3
Marks         5
dtype: int64

<h2>value_counts()</h2>

value_counts() tells us how many times each value appears

__Example:__

An HR department counts how many employees belong to each department.

<h3>AI/ML Usage</h3>

Useful for checking class balance in classification problems.

In [21]:
students["Department"].value_counts()

Department
AI    2
ML    2
DS    1
Name: count, dtype: int64